export const FILTROS_INICIAIS_PONTOS_CONTROLE = {
  nr_instrumento: '',
  proponente: '',
  municipios_beneficiados: '',
  uf: '',
  carteira_ativa: '',
  projeto_aprovado: '',
  possui_aio: '',
  coordenacao: '',
  acao: '',
  monitor: '',
  prazo_clausulas_suspensivas: '',
  prazo_emissao_lae: '',
  prazo_inicio_licitacao: '',
  prazo_conclusao_licitacao: '',
  prazo_vrpl: '',
  prazo_contratacao: '',
  prazo_solicitacao_aio: '',
  prazo_analise_tecnica_aio: '',
  prazo_analise_executiva_aio: '',
  prazo_registro_aio: '',
  prazo_emissao_os: '',
  prazo_inicio_execucao_fisica: '',
  prazo_progresso_fisico: '',
  prazo_indicio_paralisacao: '',
  status_paralisacao_obra: '',
  vistoria_in_loco_parciais: '',
  prazo_vistoria_final: '',
  obras_proximas_conclusao: '',
  registro_conclusao: '',
  vigencia: '',
  status_de_execucao_da_obra: '',
};

export const contarFiltrosAtivosPontosControle = (filtros = {}) =>
  Object.values(filtros).filter((valor) => String(valor ?? '').trim() !== '').length;
