import { useCallback, useEffect, useState } from 'react'
import { KeyRound, Link, Loader2, Power, PowerOff, X } from 'lucide-react'
import { adminUsuariosApi } from '@/api/adminUsuarios'
import { AccountBadge, StatusBadge } from './UsersTable'
import AccessCodeModal from './AccessCodeModal'
import styles from '@/pages/admin/usuarios/AdminUsuarios.module.css'

const formatar = (valor) => valor ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(valor)) : 'Nunca acessou'

export default function UserDetailsPanel({ idUsuario, onClose, onChanged }) {
  const [usuario, setUsuario] = useState(null); const [erro, setErro] = useState(''); const [codigo, setCodigo] = useState(null)
  const [busca, setBusca] = useState(''); const [opcoes, setOpcoes] = useState([]); const [ocupado, setOcupado] = useState(false)
  const carregar = useCallback(async () => { try { setUsuario(await adminUsuariosApi.detalhe(idUsuario)) } catch (e) { setErro(e?.response?.data?.detail || 'Não foi possível carregar o usuário.') } }, [idUsuario])
  useEffect(() => { Promise.resolve().then(carregar) }, [carregar])
  useEffect(() => { if (busca.trim().length < 2) return undefined; const timer = setTimeout(async () => { try { setOpcoes(await adminUsuariosApi.buscarInstrumentos(busca.trim())) } catch { setOpcoes([]) } }, 300); return () => clearTimeout(timer) }, [busca])
  const executar = async (fn) => { setOcupado(true); setErro(''); try { await fn(); await carregar(); onChanged() } catch (e) { setErro(e?.response?.data?.detail || 'Não foi possível concluir a ação.') } finally { setOcupado(false) } }
  if (!usuario && !erro) return <aside className={styles.drawer}><div className={styles.loading}><Loader2 className={styles.spin} /> Carregando...</div></aside>
  if (!usuario) return <aside className={styles.drawer}><button className={styles.close} onClick={onClose}><X /></button><p role="alert">{erro}</p></aside>
  const tecnico = usuario.perfil === 'tecnico'; const p = usuario.pendencias
  return <><div className={styles.drawerBackdrop} onClick={onClose} /><aside className={styles.drawer} aria-label={`Detalhes de ${usuario.nome}`}>
    <header className={styles.drawerHeader}><div><span>{usuario.perfil === 'admin' ? 'Administrador' : `Técnico ${usuario.codigo_tecnico ?? ''}`}</span><h2>{usuario.nome}</h2><p>{usuario.email}</p></div><button className={styles.close} onClick={onClose} aria-label="Fechar"><X /></button></header>
    {erro && <p className={styles.error} role="alert">{erro}</p>}
    <section className={styles.detailSection}><h3>Dados gerais e conta</h3><div className={styles.detailGrid}><div><small>Setor</small><strong>{usuario.setor || 'Não informado'}</strong></div><div><small>Usuário</small><StatusBadge ativo={usuario.ativo} /></div><div><small>Conta</small><AccountBadge ativa={usuario.conta_ativada} /></div><div><small>Último acesso</small><strong>{formatar(usuario.ultimo_acesso_em)}</strong></div><div><small>Criado em</small><strong>{formatar(usuario.criado_em)}</strong></div><div><small>Atualizado em</small><strong>{formatar(usuario.atualizado_em)}</strong></div><div><small>Código de acesso</small><strong>{usuario.codigo_acesso_usado_em ? `Utilizado em ${formatar(usuario.codigo_acesso_usado_em)}` : usuario.codigo_acesso_expira_em ? (new Date(usuario.codigo_acesso_expira_em) > new Date() ? `Válido até ${formatar(usuario.codigo_acesso_expira_em)}` : 'Código expirado') : 'Nenhum código vigente'}</strong></div></div></section>
    <section className={styles.detailSection}><h3>Ações administrativas</h3><div className={styles.actions}><button className={styles.primary} disabled={ocupado} onClick={() => executar(async () => setCodigo(await adminUsuariosApi.gerarCodigo(idUsuario)))}><KeyRound /> Gerar código de acesso</button><button className={styles.secondary} disabled={ocupado} onClick={() => { if (usuario.ativo && !window.confirm(`Desativar ${usuario.nome}? O histórico será preservado.`)) return; executar(() => adminUsuariosApi.alterarStatus(idUsuario, !usuario.ativo)) }}>{usuario.ativo ? <PowerOff /> : <Power />}{usuario.ativo ? 'Desativar usuário' : 'Reativar usuário'}</button></div></section>
    <section className={styles.detailSection}><div className={styles.sectionTitle}><h3>Instrumentos</h3><span>{usuario.instrumentos_ativos} ativos</span></div>{!tecnico ? <p className={styles.notice}>Administradores possuem acesso global e não dependem de vínculos individuais.</p> : <><label className={styles.instrumentSearch}><input value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Digite parte do instrumento ou proposta" /></label>{busca.trim().length >= 2 && opcoes.length > 0 && <div className={styles.options}>{opcoes.map((item) => <button key={item.nr_instrumento} onClick={() => executar(async () => { await adminUsuariosApi.vincularInstrumento(idUsuario, item.nr_instrumento); setBusca(''); setOpcoes([]) })}><Link /> <span><strong>{item.nr_instrumento}</strong><small>{item.nr_proposta || item.tipo_instrumento}</small></span></button>)}</div>}<div className={styles.links}>{usuario.instrumentos.map((item) => <div key={item.nr_instrumento}><span><strong>{item.nr_instrumento}</strong><small>{item.ativo ? 'Vínculo ativo' : 'Vínculo inativo'}</small></span><button onClick={() => executar(() => adminUsuariosApi.alterarVinculo(idUsuario, item.nr_instrumento, !item.ativo))}>{item.ativo ? 'Desativar' : 'Reativar'}</button></div>)}</div>{usuario.instrumentos.length === 0 && <p className={styles.empty}>Este técnico ainda não possui instrumentos vinculados.</p>}</>}</section>
    <section className={styles.detailSection}><div className={styles.sectionTitle}><h3>Pendências</h3><span>{p.percentual_concluido}% concluído</span></div>{tecnico ? <><div className={styles.progress}><i style={{ width: `${p.percentual_concluido}%` }} /></div><p>{p.total} total · {p.concluidas} concluídas · {p.abertas} abertas</p>{p.instrumentos.map((item) => <div className={styles.pending} key={item.identificador_instrumento}><strong>{item.identificador_instrumento}</strong><span>{item.concluidas}/{item.total} concluídas</span></div>)}{p.total === 0 && <p className={styles.empty}>Nenhuma pendência encontrada.</p>}</> : <p className={styles.notice}>O progresso de pendências é aplicável aos técnicos.</p>}</section>
    <section className={styles.detailSection}><div className={styles.sectionTitle}><h3>Revisões</h3><span>{usuario.revisoes_enviadas} enviadas</span></div>{usuario.revisoes.map((r) => <article className={styles.review} key={r.id_revisao}><div><strong>{r.identificador_instrumento}</strong><small>{r.tipo_instrumento}</small></div><span className={styles.badge}>{r.status}</span><time>{formatar(r.enviado_em || r.atualizado_em)}</time></article>)}{usuario.revisoes.length === 0 && <p className={styles.empty}>Nenhuma revisão enviada.</p>}</section>
  </aside>{codigo && <AccessCodeModal codigo={codigo.codigo} expiraEm={codigo.expira_em} onClose={() => setCodigo(null)} />}</>
}
