import { useCallback, useEffect, useState } from 'react'
import { Building2, KeyRound, Link, Loader2, Plus, Power, PowerOff, Search, Trash2, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { adminUsuariosApi } from '@/api/adminUsuarios'
import { AccountBadge, StatusBadge } from './UsersTable'
import AccessCodeModal from './AccessCodeModal'
import styles from '@/pages/admin/usuarios/AdminUsuarios.module.css'

const LIMITE_INICIAL = 5
const LIMITE_EXPANDIDO = 20
const GRUPOS = { municipios: 'Municípios', localidades: 'Localidades', coordenadas: 'Coordenadas', publico_alvo: 'Público-alvo', obras: 'Obras' }
const formatar = (valor) => valor ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(valor)) : 'Nunca acessou'

function ModalBase({ titulo, onClose, children }) {
  return <div className={styles.modalBackdrop}><section className={`${styles.modal} ${styles.formModal}`} role="dialog" aria-modal="true" aria-label={titulo}><button type="button" className={styles.close} onClick={onClose} aria-label="Fechar"><X /></button><h2>{titulo}</h2>{children}</section></div>
}

function AddInstrumentModal({ idUsuario, onClose, onAdded }) {
  const [busca, setBusca] = useState(''); const [opcoes, setOpcoes] = useState([]); const [ocupado, setOcupado] = useState(false); const [erro, setErro] = useState('')
  useEffect(() => { if (busca.trim().length < 2) return undefined; const timer = setTimeout(() => adminUsuariosApi.buscarInstrumentos(busca.trim()).then(setOpcoes).catch(() => setOpcoes([])), 300); return () => clearTimeout(timer) }, [busca])
  async function adicionar(item) { setOcupado(true); setErro(''); try { await adminUsuariosApi.vincularInstrumento(idUsuario, item.nr_instrumento); onAdded('Instrumento vinculado com sucesso.') } catch (error) { setErro(error?.response?.data?.detail || 'Não foi possível vincular o instrumento.') } finally { setOcupado(false) } }
  return <ModalBase titulo="Adicionar instrumento" onClose={onClose}><p>Digite parte do instrumento ou proposta.</p>{erro && <div className={styles.error} role="alert">{erro}</div>}<label className={styles.instrumentSearch}><Search /><input autoFocus value={busca} onChange={(e) => { setBusca(e.target.value); if (e.target.value.trim().length < 2) setOpcoes([]) }} placeholder="Digite parte do instrumento ou proposta" /></label>{opcoes.length > 0 && <div className={styles.options}>{opcoes.map((item) => <button type="button" disabled={ocupado} key={item.nr_instrumento} onClick={() => adicionar(item)}><Link /><span><strong>{item.nr_instrumento}</strong><small>{item.nr_proposta || item.tipo_instrumento}</small></span></button>)}</div>}</ModalBase>
}

function ChangeSectorModal({ usuario, onClose, onChanged }) {
  const [setores, setSetores] = useState([]); const [novo, setNovo] = useState(''); const [erro, setErro] = useState(''); const [ocupado, setOcupado] = useState(false)
  useEffect(() => { adminUsuariosApi.listarSetores().then(setSetores).catch(() => setErro('Não foi possível carregar os setores.')) }, [])
  async function salvar(event) { event.preventDefault(); setOcupado(true); setErro(''); try { await adminUsuariosApi.alterarSetor(usuario.id_usuario, Number(novo)); onChanged('Setor alterado com sucesso.') } catch (error) { setErro(error?.response?.data?.detail || 'Não foi possível alterar o setor.') } finally { setOcupado(false) } }
  return <ModalBase titulo="Alterar setor" onClose={onClose}><p>Setor atual: <strong>{usuario.setor || 'Não informado'}</strong></p>{erro && <div className={styles.error} role="alert">{erro}</div>}<form onSubmit={salvar}><label>Novo setor<select required value={novo} onChange={(e) => setNovo(e.target.value)}><option value="">Selecione</option>{setores.filter((s) => s.id_setor !== usuario.id_setor).map((s) => <option key={s.id_setor} value={s.id_setor}>{s.nome}</option>)}</select></label><div className={styles.modalActions}><button type="button" className={styles.secondary} onClick={onClose}>Cancelar</button><button type="submit" className={styles.primary} disabled={ocupado || !novo}>{ocupado && <Loader2 className={styles.spin} />}Alterar setor</button></div></form></ModalBase>
}

function CancelDraftModal({ usuario, item, onClose, onConfirm, ocupado }) {
  return <ModalBase titulo="Cancelar rascunho?" onClose={onClose}><p><strong>Instrumento {item.identificador_instrumento}</strong><br />Técnico: {usuario.nome}</p><p>As alterações ainda não enviadas serão descartadas e o instrumento voltará ao estado anterior.</p><div className={styles.modalActions}><button type="button" className={styles.secondary} onClick={onClose}>Voltar</button><button type="button" className={styles.dangerButton} disabled={ocupado} onClick={onConfirm}>{ocupado && <Loader2 className={styles.spin} />}Cancelar rascunho</button></div></ModalBase>
}

function Paginacao({ total, offset, limit, onChange }) {
  if (total <= limit) return null
  return <div className={styles.inlinePagination}><button type="button" disabled={offset === 0} onClick={() => onChange(Math.max(0, offset - limit))}>Anterior</button><span>{Math.floor(offset / limit) + 1} de {Math.ceil(total / limit)}</span><button type="button" disabled={offset + limit >= total} onClick={() => onChange(offset + limit)}>Próxima</button></div>
}

export default function UserDetailsPanel({ idUsuario, onClose, onChanged }) {
  const navigate = useNavigate()
  const [usuario, setUsuario] = useState(null); const [erro, setErro] = useState(''); const [codigo, setCodigo] = useState(null); const [ocupado, setOcupado] = useState(false)
  const [buscaVinculos, setBuscaVinculos] = useState(''); const [buscaPendencias, setBuscaPendencias] = useState('')
  const [expandidos, setExpandidos] = useState({ instrumentos: false, pendencias: false, rascunhos: false, revisoes: false })
  const [offsets, setOffsets] = useState({ instrumentos: 0, pendencias: 0, rascunhos: 0, revisoes: 0 })
  const [rascunhos, setRascunhos] = useState({ items: [], total: 0 }); const [detalhes, setDetalhes] = useState({}); const [pendenciaAberta, setPendenciaAberta] = useState(null)
  const [modal, setModal] = useState(null); const [versao, setVersao] = useState(0); const [mensagem, setMensagem] = useState('')
  const usuarioCarregado = Boolean(usuario); const tecnicoCarregado = usuario?.perfil === 'tecnico'
  const carregar = useCallback(async () => { setErro(''); try { setUsuario(await adminUsuariosApi.detalhe(idUsuario)) } catch (e) { setErro(e?.response?.data?.detail || 'Não foi possível carregar o usuário.') } }, [idUsuario])
  useEffect(() => { Promise.resolve().then(carregar) }, [carregar, versao])
  const limite = (secao) => expandidos[secao] ? LIMITE_EXPANDIDO : LIMITE_INICIAL
  const limiteInstrumentos = expandidos.instrumentos ? LIMITE_EXPANDIDO : LIMITE_INICIAL
  const limitePendencias = expandidos.pendencias ? LIMITE_EXPANDIDO : LIMITE_INICIAL
  const limiteRascunhos = expandidos.rascunhos ? LIMITE_EXPANDIDO : LIMITE_INICIAL
  const limiteRevisoes = expandidos.revisoes ? LIMITE_EXPANDIDO : LIMITE_INICIAL
  useEffect(() => { if (!usuarioCarregado) return undefined; const timer = setTimeout(() => adminUsuariosApi.instrumentosUsuario(idUsuario, { busca: buscaVinculos || undefined, limit: limiteInstrumentos, offset: offsets.instrumentos }).then((r) => setUsuario((u) => ({ ...u, instrumentos: r.items, instrumentos_total: r.total }))).catch(() => {}), buscaVinculos ? 300 : 0); return () => clearTimeout(timer) }, [buscaVinculos, idUsuario, limiteInstrumentos, offsets.instrumentos, usuarioCarregado, versao])
  useEffect(() => { if (!tecnicoCarregado) return undefined; const timer = setTimeout(() => adminUsuariosApi.pendenciasUsuario(idUsuario, { busca: buscaPendencias || undefined, limit: limitePendencias, offset: offsets.pendencias }).then((r) => setUsuario((u) => ({ ...u, pendencias: r }))).catch(() => {}), buscaPendencias ? 300 : 0); return () => clearTimeout(timer) }, [buscaPendencias, idUsuario, limitePendencias, offsets.pendencias, tecnicoCarregado, versao])
  useEffect(() => { if (!tecnicoCarregado) return; adminUsuariosApi.rascunhosUsuario(idUsuario, { limit: limiteRascunhos, offset: offsets.rascunhos }).then(setRascunhos).catch(() => {}) }, [idUsuario, limiteRascunhos, offsets.rascunhos, tecnicoCarregado, versao])
  useEffect(() => { if (!usuarioCarregado) return; adminUsuariosApi.revisoesUsuario(idUsuario, { limit: limiteRevisoes, offset: offsets.revisoes }).then((r) => setUsuario((u) => ({ ...u, revisoes: r.items, revisoes_total: r.total }))).catch(() => {}) }, [idUsuario, limiteRevisoes, offsets.revisoes, usuarioCarregado, versao])
  function alternar(secao) { setExpandidos((v) => ({ ...v, [secao]: !v[secao] })); setOffsets((v) => ({ ...v, [secao]: 0 })) }
  function atualizar(sucesso = '') { setModal(null); setMensagem(sucesso); setVersao((v) => v + 1); onChanged() }
  async function executar(fn, sucesso = '') { setOcupado(true); setErro(''); setMensagem(''); try { await fn(); atualizar(sucesso) } catch (e) { setErro(e?.response?.data?.detail || 'Não foi possível concluir a ação.') } finally { setOcupado(false) } }
  async function abrirPendencias(item) { const id = item.identificador_instrumento; if (pendenciaAberta === id) { setPendenciaAberta(null); return } setPendenciaAberta(id); if (detalhes[id]) return; try { const detalhe = await adminUsuariosApi.detalharPendencias(idUsuario, id); setDetalhes((v) => ({ ...v, [id]: detalhe })) } catch (e) { setErro(e?.response?.data?.detail || 'Não foi possível detalhar as pendências.') } }
  if (!usuario && !erro) return <aside className={styles.drawer}><div className={styles.loading}><Loader2 className={styles.spin} /> Carregando...</div></aside>
  if (!usuario) return <aside className={styles.drawer}><button className={styles.close} onClick={onClose}><X /></button><p role="alert">{erro}</p></aside>
  const tecnico = usuario.perfil === 'tecnico'; const p = usuario.pendencias
  return <><div className={styles.drawerBackdrop} onClick={onClose} /><aside className={styles.drawer} aria-label={`Detalhes de ${usuario.nome}`}>
    <header className={styles.drawerHeader}><div><span>{usuario.perfil === 'admin' ? 'Administrador' : `Técnico ${usuario.codigo_tecnico ?? ''}`}</span><h2>{usuario.nome}</h2><p>{usuario.email}</p></div><button className={styles.close} onClick={onClose} aria-label="Fechar"><X /></button></header>
    {erro && <p className={styles.error} role="alert">{erro}</p>}{mensagem && <p className={styles.successMessage} role="status">{mensagem}</p>}
    <section className={styles.detailSection}><h3>Dados do usuário</h3><div className={styles.detailGrid}><div><small>Setor</small><strong>{usuario.setor || 'Não informado'}</strong></div><div><small>Usuário</small><StatusBadge ativo={usuario.ativo} /></div><div><small>Conta</small><AccountBadge ativa={usuario.conta_ativada} /></div><div><small>Último acesso</small><strong>{formatar(usuario.ultimo_acesso_em)}</strong></div><div><small>Criado em</small><strong>{formatar(usuario.criado_em)}</strong></div><div><small>Atualizado em</small><strong>{formatar(usuario.atualizado_em)}</strong></div><div><small>Código de acesso</small><strong>{usuario.codigo_acesso_usado_em ? `Utilizado em ${formatar(usuario.codigo_acesso_usado_em)}` : usuario.codigo_acesso_expira_em ? (new Date(usuario.codigo_acesso_expira_em) > new Date() ? `Válido até ${formatar(usuario.codigo_acesso_expira_em)}` : 'Código expirado') : 'Nenhum código vigente'}</strong></div></div></section>
    <section className={styles.detailSection}><h3>Ações administrativas</h3><div className={styles.actions}><button className={styles.primary} disabled={ocupado} onClick={() => executar(async () => setCodigo(await adminUsuariosApi.gerarCodigo(idUsuario)))}><KeyRound /> Gerar código de acesso</button><button className={styles.secondary} disabled={ocupado} onClick={() => { if (usuario.ativo && !window.confirm(`Desativar ${usuario.nome}? O histórico será preservado.`)) return; executar(() => adminUsuariosApi.alterarStatus(idUsuario, !usuario.ativo)) }}>{usuario.ativo ? <PowerOff /> : <Power />}{usuario.ativo ? 'Desativar usuário' : 'Reativar usuário'}</button>{tecnico && <button className={styles.secondary} onClick={() => setModal('setor')}><Building2 /> Alterar setor</button>}</div></section>
    <section className={styles.detailSection}><div className={styles.sectionTitle}><h3>Instrumentos</h3><span>{usuario.instrumentos_total ?? usuario.instrumentos_ativos} no total</span></div>{!tecnico ? <p className={styles.notice}>Administradores possuem acesso global e não dependem de vínculos individuais.</p> : <><label className={styles.instrumentSearch}><Search /><input value={buscaVinculos} onChange={(e) => { setBuscaVinculos(e.target.value); setOffsets((v) => ({ ...v, instrumentos: 0 })) }} placeholder="Buscar nos instrumentos vinculados" /></label><div className={styles.links}>{usuario.instrumentos.map((item) => <div key={item.nr_instrumento}><span><strong>{item.nr_instrumento}</strong><small>{item.ativo ? 'Vínculo ativo' : 'Vínculo inativo'}</small></span><button onClick={() => executar(() => adminUsuariosApi.alterarVinculo(idUsuario, item.nr_instrumento, !item.ativo))}>{item.ativo ? 'Desativar' : 'Reativar'}</button></div>)}</div>{usuario.instrumentos.length === 0 && <p className={styles.empty}>Nenhum instrumento encontrado.</p>}<Paginacao total={usuario.instrumentos_total || 0} offset={offsets.instrumentos} limit={limite('instrumentos')} onChange={(n) => setOffsets((v) => ({ ...v, instrumentos: n }))} /><div className={styles.sectionFooter}><button className={styles.secondary} onClick={() => setModal('instrumento')}><Plus /> Adicionar instrumento</button>{(usuario.instrumentos_total ?? 0) > 5 && <button className={styles.listToggle} onClick={() => alternar('instrumentos')}>{expandidos.instrumentos ? 'Mostrar menos' : 'Ver todos os instrumentos'}</button>}</div></>}</section>
    <section className={styles.detailSection}><div className={styles.sectionTitle}><h3>Pendências</h3><span>{p.percentual_concluido}% concluído</span></div>{tecnico ? <><div className={styles.progress}><i style={{ width: `${p.percentual_concluido}%` }} /></div><p>{p.total} total · {p.concluidas} concluídas · {p.abertas} abertas</p><label className={styles.instrumentSearch}><Search /><input value={buscaPendencias} onChange={(e) => { setBuscaPendencias(e.target.value); setOffsets((v) => ({ ...v, pendencias: 0 })) }} placeholder="Buscar por nº do instrumento" /></label>{p.instrumentos.map((item) => <div className={styles.pendingBlock} key={item.identificador_instrumento}><div className={styles.pending}><strong>{item.identificador_instrumento}</strong><span>{item.concluidas}/{item.total} concluídas</span><button type="button" onClick={() => abrirPendencias(item)}>{pendenciaAberta === item.identificador_instrumento ? 'Ocultar pendências' : 'Ver pendências'}</button></div>{pendenciaAberta === item.identificador_instrumento && <div className={styles.pendingDetails}>{!detalhes[item.identificador_instrumento] ? <Loader2 className={styles.spin} /> : <dl>{Object.entries(GRUPOS).map(([chave, nome]) => <div key={chave}><dt>{nome}</dt><dd>{detalhes[item.identificador_instrumento].grupos[chave]}</dd></div>)}</dl>}</div>}</div>)}{p.instrumentos.length === 0 && <p className={styles.empty}>Nenhuma pendência encontrada.</p>}<Paginacao total={p.instrumentos_total || 0} offset={offsets.pendencias} limit={limite('pendencias')} onChange={(n) => setOffsets((v) => ({ ...v, pendencias: n }))} />{(p.instrumentos_total ?? 0) > 5 && <button className={styles.listToggle} onClick={() => alternar('pendencias')}>{expandidos.pendencias ? 'Mostrar menos' : 'Ver todas as pendências'}</button>}</> : <p className={styles.notice}>O progresso de pendências é aplicável aos técnicos.</p>}</section>
    {tecnico && <section className={styles.detailSection}><div className={styles.sectionTitle}><h3>Rascunhos em aberto</h3><span>{rascunhos.total}</span></div>{rascunhos.items.map((item) => <article className={styles.review} key={item.id_revisao}><div><strong>{item.identificador_instrumento}</strong><small>{item.tipo_instrumento_label}</small><time>Atualizado em {formatar(item.atualizado_em)}</time></div><button type="button" className={styles.dangerLink} onClick={() => setModal(item)}><Trash2 /> Cancelar rascunho</button></article>)}{rascunhos.items.length === 0 && <p className={styles.empty}>Nenhum rascunho em aberto.</p>}<Paginacao total={rascunhos.total} offset={offsets.rascunhos} limit={limite('rascunhos')} onChange={(n) => setOffsets((v) => ({ ...v, rascunhos: n }))} />{rascunhos.total > 5 && <button className={styles.listToggle} onClick={() => alternar('rascunhos')}>{expandidos.rascunhos ? 'Mostrar menos' : 'Ver todos os rascunhos'}</button>}</section>}
    <section className={styles.detailSection}><div className={styles.sectionTitle}><h3>Revisões</h3><span>{usuario.revisoes_total ?? usuario.revisoes_enviadas} enviadas</span></div>{usuario.revisoes.map((r) => <article className={styles.review} key={r.id_revisao}><div><strong>{r.identificador_instrumento}</strong><small>{r.tipo_instrumento}</small><time>{formatar(r.enviado_em || r.atualizado_em)}</time></div><button type="button" onClick={() => navigate(`/revisao-instrumento/${encodeURIComponent(r.identificador_instrumento)}/revisoes/${r.id_revisao}`)}>Visualizar revisão</button></article>)}{usuario.revisoes.length === 0 && <p className={styles.empty}>Nenhuma revisão enviada.</p>}<Paginacao total={usuario.revisoes_total || 0} offset={offsets.revisoes} limit={limite('revisoes')} onChange={(n) => setOffsets((v) => ({ ...v, revisoes: n }))} />{(usuario.revisoes_total ?? 0) > 5 && <button className={styles.listToggle} onClick={() => alternar('revisoes')}>{expandidos.revisoes ? 'Mostrar menos' : 'Ver todas as revisões'}</button>}</section>
  </aside>{codigo && <AccessCodeModal codigo={codigo.codigo} expiraEm={codigo.expira_em} onClose={() => setCodigo(null)} />}{modal === 'instrumento' && <AddInstrumentModal idUsuario={idUsuario} onClose={() => setModal(null)} onAdded={atualizar} />}{modal === 'setor' && <ChangeSectorModal usuario={usuario} onClose={() => setModal(null)} onChanged={atualizar} />}{typeof modal === 'object' && modal?.id_revisao && <CancelDraftModal usuario={usuario} item={modal} ocupado={ocupado} onClose={() => setModal(null)} onConfirm={() => executar(() => adminUsuariosApi.cancelarRascunho(idUsuario, modal.id_revisao), 'Rascunho cancelado com sucesso.')} />}</>
}
